# Generated by Django 4.1.2 on 2022-10-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='descripcionPerfil',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='etiqueta',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
