# Generated by Django 4.1.2 on 2022-10-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='descripcion',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
