# Generated by Django 4.1.2 on 2022-10-26 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_productos_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('reporte', models.TextField(max_length=200)),
                ('prioridad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.prioridadincidencia')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.productos')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tecnicoasignado')),
            ],
        ),
    ]
