# Generated by Django 4.1.2 on 2022-10-26 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_clientes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelTable(
            name='clientes',
            table='cliente',
        ),
    ]
