# Generated by Django 4.1.2 on 2022-10-26 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_clientes_options_alter_clientes_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='prioridad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.prioridadincidencia'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.productos'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.tecnicoasignado'),
        ),
    ]
