# Generated by Django 4.1.2 on 2022-10-27 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_clientes_fechareporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='correo',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='numero',
            field=models.IntegerField(null=True),
        ),
    ]
